# Generated by Django 4.1.3 on 2022-11-18 08:04

import ads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(default=True, validators=[ads.validators.not_published]),
        ),
    ]
