# Generated by Django 4.1.3 on 2022-11-16 07:36

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[user.validators.check_birth_date]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Регистрация с домена rambler запрещена.', regex='@rambler.ru')], verbose_name='email address'),
        ),
    ]
